export const ERROR_TYPE = {
	ERROR_BOUNDARY: 'ERROR_BOUNDARY',
	VALIDATION_FAILURE: 'VALIDATION_FAILURE',
	NETWORK_FAILURE: 'NETWORK_FAILURE',
} as const;

export const ERROR_REASON = {
	RENDERING_FAILURE: 'RENDERING_FAILURE',
	INVALID_STAGE_NUMBER: 'INVALID_STAGE_NUMBER',
	STAGE_DATA_LOAD_FAILURE: 'STAGE_DATA_LOAD_FAILURE',
	INVALID_GAME_DATA: 'INVALID_GAME_DATA',
} as const;

export const ERROR_TYPE_FOR_REASON = {
	RENDERING_FAILURE: ERROR_TYPE.ERROR_BOUNDARY,
	INVALID_STAGE_NUMBER: ERROR_TYPE.VALIDATION_FAILURE,
	STAGE_DATA_LOAD_FAILURE: ERROR_TYPE.NETWORK_FAILURE,
	INVALID_GAME_DATA: ERROR_TYPE.VALIDATION_FAILURE,
};

export const ERROR_SLICE = {
	DISPLAY: 'DISPLAY',
	SOUND: 'SOUND',
	STAGE: 'STAGE',
	GAME: 'GAME',
} as const;
