export const SCREEN = {
	HOME: 'HOME_SCREEN',
	GAME: 'GAME_SCREEN',
};

export const POPUP = {
	SOUND_ALERT: 'SOUND_ALERT_POPUP',
	ENDING_ALERT: 'ENDING_ALERT_POPUP',
	RESULT: 'RESULT_POPUP',
	STAGE: 'STAGE_POPUP',
	EXIT_GAME: 'EXIT_GAME_POPUP',
};
