export const ANIMATION_DURATION = {
	MOVING_HEART: 200,
	CRUSHED_HEART: 500,
	FALLING_HEART: 100,
	ENDING_ALERT: 800,
	BONUS_SCORE: 400,
	SWAP_HINT: 800,
	RESET_BOARD_ALERT: 2000,
	CONFETTI: 3000,
};

export const ANIMATION_DELAY = {
	ENDING_ALERT_FADEIN: 0,
	ENDING_ALERT_FADEOUT: 1000,
	SWAP_HINT: 3000,
};

export const TEXT = {
	ENDING_ALERT_FINISH: 'Finish',
	ENDING_ALERT_BONUS: 'Bonus',
	RESULT_WIN: 'Victory',
	RESULT_LOSE: 'Defeat',
	GAME_CLEAR: 'The End',
};
